name: flutter_stateless_chessboard
description: A Chessboard Widget for Flutter. This package provides just the chessboard. The game logic can be implemented using chess library.
version: 0.0.4
homepage: https://github.com/varunpvp/flutter_chessboard

environment:
  sdk: ">=2.12.2 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  chess_vectors_flutter: ^1.0.16
  chess: ^0.7.0
  dartz: ^0.10.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
